version: '3.3'
services:
  # NGINX webservers with nginx-demo hello page
  web1:
      hostname: web1
      build: nginx-hello
      volumes:
        - ./nginx-hello/etc/nginx:/etc/nginx
        - ./nginx-hello/usr/share/nginx/html:/usr/share/nginx/html
      expose:
        - "80"
  web2:
      hostname: web2
      build: nginx-hello
      volumes:
        - ./nginx-hello/etc/nginx:/etc/nginx
        - ./nginx-hello/usr/share/nginx/html:/usr/share/nginx/html
      ports:
        - "80"
  # EDITS-START
  # Simply Add another server like so:    
  web3:
      hostname: web3
      build: nginx-hello
      volumes:
        - ./nginx-hello/etc/nginx:/etc/nginx
        - ./nginx-hello/usr/share/nginx/html:/usr/share/nginx/html
      ports:
        - "80"
  # EDITS-END  
  # NGINX Plus Load Balancer       
  nginx-plus:
      hostname: nginx-plus
      build: nginx-plus
      links:
          - web1:web1
          - web2:web2
          - web3:web3
      volumes:
          - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
          - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
          - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 8080:8080
          - 80:80
          - 443:443
      restart: always